
import java.text.SimpleDateFormat;
import java.sql.*;
import javax.swing.JOptionPane;
import proje.Connectionprovider;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author FEVZİYE NUR KS1
 */
public class odunckitapalma extends javax.swing.JFrame {

    /**
     * Creates new form odunckitapalma
     */
    public odunckitapalma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblkitapno = new javax.swing.JLabel();
        lblogrencino = new javax.swing.JLabel();
        lblkayit = new javax.swing.JLabel();
        lbliade = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        lblkitapno.setBackground(new java.awt.Color(0, 0, 0));
        lblkitapno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblkitapno.setForeground(new java.awt.Color(0, 0, 0));
        lblkitapno.setText("Kitap Adı :");

        lblogrencino.setBackground(new java.awt.Color(0, 0, 0));
        lblogrencino.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblogrencino.setForeground(new java.awt.Color(0, 0, 0));
        lblogrencino.setText("Öğrenci No :");

        lblkayit.setBackground(new java.awt.Color(0, 0, 0));
        lblkayit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblkayit.setForeground(new java.awt.Color(0, 0, 0));
        lblkayit.setText("Kayıt Tarihi :");

        lbliade.setBackground(new java.awt.Color(0, 0, 0));
        lbliade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbliade.setForeground(new java.awt.Color(0, 0, 0));
        lbliade.setText("İade Tarihi :");

        jTextField1.setForeground(new java.awt.Color(0, 0, 0));

        jTextField2.setForeground(new java.awt.Color(0, 0, 0));

        jDateChooser1.setForeground(new java.awt.Color(255, 255, 204));

        jDateChooser2.setForeground(new java.awt.Color(255, 255, 204));

        jButton1.setText("KAYIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ÇIKIŞ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblogrencino, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblkitapno, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblkayit)
                        .addGap(51, 51, 51)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbliade, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblkitapno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblogrencino, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblkayit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbliade, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
        setVisible(false);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
    String kitap_adi = jTextField1.getText();
    String ogrenci_no = jTextField2.getText();
    String kayit_tarihi = dFormat.format(jDateChooser1.getDate());
    String iade_tarihi = dFormat.format(jDateChooser2.getDate());
    String returnkitap = "hayır";
    
    

    String insertSql = "INSERT INTO kitaplar (kitap_adi, ogrenci_no, kayit_tarihi, iade_tarihi) VALUES (?, ?, ?, ?)";
    String selectSql = "SELECT * FROM kitaplar WHERE odunc_kitap = ?";
    String insertOduncSql = "INSERT INTO kitaplar (kitap_adi,  ogrenci_no, kayit_tarihi, iade_tarihi) VALUES (?, ?, ?, ?)";

    try {
    Connection con = DatabaseConnection.getConnection();
    PreparedStatement insertStatement = con.prepareStatement(insertOduncSql);
    insertStatement.setString(1, kitap_adi);
    insertStatement.setString(2, ogrenci_no);
    insertStatement.setString(3, kayit_tarihi);
    insertStatement.setString(4, iade_tarihi);

    int affectedRows = insertStatement.executeUpdate();

    if (affectedRows > 0) {
        PreparedStatement selectStatement = con.prepareStatement(selectSql);
        selectStatement.setString(1, ogrenci_no);
        ResultSet rsl = selectStatement.executeQuery();

        if (rsl.next()) {
            PreparedStatement insertKitaplarStatement = con.prepareStatement(insertSql);
            insertKitaplarStatement.setString(1, kitap_adi);
            insertKitaplarStatement.setString(2, ogrenci_no);
            insertKitaplarStatement.setString(3, kayit_tarihi);
            insertKitaplarStatement.setString(4, iade_tarihi);
            insertKitaplarStatement.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Kitap Başarıyla Kaydedildi");
            setVisible(false);
            new odunckitapalma().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Yanlış Öğrenci No");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Bağlantı Hatası veya Yanlış Kitap No");
    }
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Veritabanı Hatası veya İşlem Başarısız: " + e.getMessage());
    e.printStackTrace(); // Hatanın tam yığın izini yazdır
    setVisible(false);
    new odunckitapalma().setVisible(true);
}




    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(odunckitapalma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(odunckitapalma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(odunckitapalma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(odunckitapalma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new odunckitapalma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbliade;
    private javax.swing.JLabel lblkayit;
    private javax.swing.JLabel lblkitapno;
    private javax.swing.JLabel lblogrencino;
    // End of variables declaration//GEN-END:variables
}
